### PR TITLE
Backpack stacks when collected multiple times

### PR DESCRIPTION
**Pull request by coavins**
The backpack can be collected multiple times. Each backpack increases max ammo by the specified amount. Each ammo type has its own backpack.

Backpack is configurable:
* Max number of backpacks for each ammo type
* Initial max ammo for each ammo type
* Amount of max ammo that the backpack awards, separately for each ammo type

TODO:
* Actually put more than one backpack in the item pool
* Add the settings to the yaml and use them
* Finish implementing a setting to allow NOT splitting the backpack by ammo type

I think I covered everything on doom's end, but I need help with the stuff on the AP side.

### CODE REVIEW

**Comment by Daivuk** [comment]
Sorry totally missed the notification on this. Will take a look once I have time.

**Comment by Daivuk** [comment]
ooohhh wait yea. bad news, code is very different now. You used master right? I was doing latest stuff into branch `heretic`. I will merge it into master. You'll have various changes to do. Sorry. Should have merged back more frequently into main.

**Comment by Daivuk** [comment]
and thanks for the contribution, I hope you can rebase and resolve this

**Comment by Daivuk** [comment]
Hi, looking at this again. If you're still up to it, can you clean up by rebasing `master`? What options need to be added on the apworld?

**Comment by KScl** [comment]
Closing in favor of #18 since this hasn't been updated in nearly a year.

**Pull request closed without merging**
